# Generated by Django 4.0.4 on 2022-04-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodapp', '0002_rename_neighborhoood_neighborhood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='User',
            new_name='user',
        ),
    ]
