# Generated by Django 4.0.4 on 2022-04-18 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhoodapp', '0004_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='titile',
            new_name='title',
        ),
    ]
